-- Migration: create departments table
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    company_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT uk_departments_company_name UNIQUE (company_id, name),
    CONSTRAINT fk_departments_company FOREIGN KEY (company_id) REFERENCES companies(id)
);
