-- Migration: create designations table
CREATE TABLE designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    company_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT uk_designations_company_name UNIQUE (company_id, name),
    CONSTRAINT fk_designations_company FOREIGN KEY (company_id) REFERENCES companies(id)
    ,CONSTRAINT fk_designations_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
